version: "3.4"
services:
  vpn:
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      #- "8112:8112" # deluge
      #- "8112:9091" # transmission
      - "8112:8112" # qbittorrent
      - "52629:52629"
      - "52629:52629/udp"
      - "9117:9117" # jackett
    dns:
      - 1.1.1.1
    command: '-f "" -r 192.168.0.0/24 -r 172.0.0.0/8' # enable firewall and route local network traffic

#  deluge:
#    image: linuxserver/deluge:latest
#    restart: unless-stopped
#    network_mode: service:vpn # run on the vpn network
#    environment:
#      - PUID=${PUID} # default user id, defined in .env
#      - PGID=${PGID} # default group id, defined in .env
#      - TZ=${TZ} # timezone, defined in .env
#    volumes:
#      - ${MEDIA_ROOT}/downloads:/downloads # downloads folder
#      - ${ROOT}/config/deluge:/config # config files
#    depends_on:
#      - vpn

#  transmission:
#    image: lscr.io/linuxserver/transmission
#    network_mode: service:vpn
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#      - TRANSMISSION_WEB_HOME=/flood-for-transmission/
##      - WHITELIST=127.0.0.1,192.168.*.*
#      - USER=admin
#      - PASS=admin
#    volumes:
#      - ${ROOT}/config/transmission:/config
#      - ${MEDIA_ROOT}/downloads:/downloads
#      - ${MEDIA_ROOT}/downloads/torrent-blackhole:/watch
#    depends_on:
#      - vpn
#    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    network_mode: service:vpn # run through vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8112
    volumes:
      - ${ROOT}/config/qbittorrent:/config
      - ${MEDIA_ROOT}/downloads:/downloads
    depends_on:
      - vpn
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    network_mode: service:vpn # run through vpn
    restart: unless-stopped
#    ports:
#      - "9117:9117"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${MEDIA_ROOT}/complete/tv:/tv # tv shows folder
      - ${MEDIA_ROOT}/downloads:/downloads # download folder

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${MEDIA_ROOT}/complete/movies:/movies # movies folder
      - ${MEDIA_ROOT}/downloads:/downloads # download folder

#  plex-server:
#    image: plexinc/pms-docker:latest
#    restart: unless-stopped
#    environment:
#      - TZ=${TZ} # timezone, defined in .env
#    network_mode: host
#    volumes:
#      - ${ROOT}/config/plex/db:/config # plex database
#      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
#      - ${MEDIA_ROOT}/complete:/data # media library

  bazarr:
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${MEDIA_ROOT}/complete/movies:/movies # movies folder
      - ${MEDIA_ROOT}/complete/tv:/tv # tv shows folder
    ports:
      - "6767:6767"

  organizr:
    image: organizr/organizr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - fpm=false #true or false | using true will provide better performance
      - branch=v2-master #v2-master or #v2-develop
    volumes:
      - ${ROOT}/config/organizr:/config
    ports:
      - "8789:80"
    restart: unless-stopped
