version: "3.4"
services:
  vpn:
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: always
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - "8112:8112" # qbittorrent
      - "55909:55909"
      - "55909:55909/udp"
      - "9117:9117" # jackett
      - "5800:5800" # firefox
    command: '-f "" -r 192.168.0.0/16 -r 172.0.0.0/8 -p 55909' # enable firewall and route local network traffic
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  qbittorrent:
    image: gtjamesa/qbittorrent
    build:
      context: .docker/vuetorrent
      dockerfile: Dockerfile
    network_mode: service:vpn # run through vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8112
    volumes:
      - ${ROOT}/config/qbittorrent:/config
      - ${MEDIA_ROOT}/downloads:/downloads
    depends_on:
      - vpn
    restart: always

  jackett:
    image: linuxserver/jackett:latest
    network_mode: service:vpn # run through vpn
    restart: always
#    ports:
#      - "9117:9117"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files

  sonarr:
    image: linuxserver/sonarr:latest
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${MEDIA_ROOT}/complete/tv:/tv # tv shows folder
      - ${MEDIA_ROOT}/downloads:/downloads # download folder

  radarr:
    image: linuxserver/radarr:latest
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${MEDIA_ROOT}/complete/movies:/movies # movies folder
      - ${MEDIA_ROOT}/downloads:/downloads # download folder

#  plex-server:
#    image: plexinc/pms-docker:latest
#    restart: always
#    environment:
#      - TZ=${TZ} # timezone, defined in .env
#    network_mode: host
#    volumes:
#      - ${ROOT}/config/plex/db:/config # plex database
#      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
#      - ${MEDIA_ROOT}/complete:/data # media library

  bazarr:
    image: linuxserver/bazarr
    restart: always
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${MEDIA_ROOT}/complete/movies:/movies # movies folder
      - ${MEDIA_ROOT}/complete/tv:/tv # tv shows folder
    ports:
      - "6767:6767"

  organizr:
    image: organizr/organizr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - fpm=false #true or false | using true will provide better performance
      - branch=v2-master #v2-master or #v2-develop
    volumes:
      - ${ROOT}/config/organizr:/config
    ports:
      - "8789:80"
    restart: always

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - "8191:8191"
    restart: always

  firefox:
    image: jlesage/firefox:v1.17.1
    network_mode: service:vpn # run through vpn
    environment:
      - USER_ID=${PUID} # default user id, defined in .env
      - GROUP_ID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - KEEP_APP_RUNNING=1
    volumes:
      - ${ROOT}/config/firefox:/config:rw
#    ports:
#      - "5800:5800"
    depends_on:
      - vpn
    restart: always
    shm_size: 2g

