version: '3.8'
services:
  vpn:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
      - "8112:8112" # qbittorrent
      - "55909:55909"
      - "55909:55909/udp"
      - "9117:9117" # jackett
      - "5800:5800" # firefox
      - "8191:8191" # flaresolverr
      - "4444:4444"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  client:
    image: alpine:3.15
    network_mode: service:vpn
    command: ["tail", "-f", "/dev/null"]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8112
    depends_on:
      - vpn
    restart: always

  jackett:
    image: linuxserver/jackett:v0.22.207-ls444
    network_mode: service:vpn # run through vpn
    restart: always
    #    ports:
    #      - "9117:9117"
    #    extra_hosts:
    #      - "host.docker.internal:host-gateway"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ./config/jackett:/config # config files
